### ISSUE TITLE
Config options not being used

### ISSUE THREAD

**Issue by zachwolf** [gruntjs/grunt-contrib-compass#123]
I'm trying to set up dev and dist environments, but the compiled CSS is the same regardless of what options I use. My grunt file is based on the example provided:

```
module.exports = function(grunt) {

  grunt.initConfig({
    compass: {
      dist: {
        options: {
          outputStyle: 'compressed',
          noLineComments: true
        }
      },
      dev: {
        options: {
          outputStyle: 'expanded',
          watch: false
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-compass');

  grunt.registerTask('dev', ['compass:dev']);
  grunt.registerTask('default', ['compass:dist']);

};
```

No matter what `outputStyle` option is used, the CSS is `expanded`. I have the latest versions of Grunt and Node. Does anyone know what could be going wrong here?

**Comment by jamiedgordon** [comment]
If you want it to just recompile every time, use the force option (force:true in grunt).
Otherwise, use a different target directory for your different targets!

Any developer who regularly works with compiled languages will tell you not to use the same output paths for both debug and release builds. :)

If you want to request the feature to track and check grunt/command line config as well as file changes, it would probably be a compass feature, not grunt-contrib-compass. But what you're asking for is not a small change and would increase all compile times.
