### ISSUE TITLE
Compass from RVM gemset

### ISSUE THREAD

**Issue by michaek** [gruntjs/grunt-contrib-compass#49]
Do you know of a way to convince Grunt to use the binaries from an RVM gemset instead of system Ruby binaries? 

I'm attempting to use my Gemfile/gemset to manage Compass-related dependencies, but my Grunt task is consistently invoking the compass installed with the system Ruby. (From my login shell, all works as expected.)

Thanks!

**Comment by yaron-idan** [comment]
Hi, I have a similar problem to what described here, and I wanted to know if any of the people who posted here encountered it (and hopefully overcome it).
When running grunt with compass and rvm, as described in the original issue, and it works fine.
However, I'm in the process of writing our server configuration in Ansible, and when running the commands as an Ansible playbook I'm getting an error since the playbook calls the system-wide instance of rvm, and not the one used to install compass.
Is there anyway to direct grunt-contrib-compass to use a specific RVM and not the system's default one?
